### ISSUE TITLE
Add functionality to reduce foliage the same as in the Biomass Insects/PnET connection

### ISSUE THREAD

**Issue by llmorreale** [LANDIS-II-Foundation/Extension-Land-Use-Change#12]
Comment from Brian Miranda (the curator of PnET-Succession): 
The way Biomass Insects interacts with PnET-Succession is through a reduction in foliage.  There is a CohortDefoliation function linked through the Biomass Library that is used to return a proportional reduction in foliage.  This reduction in foliage has a resulting impact on photosynthesis and the resulting NPP, but it is an indirect reduction to NPP.  If the reductions you want to include from LandUse+ are actually defoliation events, then you could directly use this same functionality.  You would just add an overriding function to LU+ that defines how the proportional reduction should be determined for each cohort on each cell (i.e., your "prescription").  CohortDefoliation works with both PnET-Succession and Biomass Succession though each uses the information from the function differently.

**Comment by achmurzy** [comment]
Hi Luca, I added some functionality to LU+ in the file 'InsectDefoliant.cs'. It calls a function 'DefoliateCohort' from Line 34 of Defoliate.cs in the Insects extension. This is all that is required as far as I can tell. Brian above mentions functionality from BiomassCohorts (class 'CohortDefoliation') but this shouldn't concern us unless we wish to change the way the Insect extension defoliates in the context of LU+, in which case we would need to override certain functionality as he mentioned. Otherwise, instantiating an 'InsectDefoliant' object and calling the 'InsectDefoliate' function on the ActiveSite should be sufficient.

**Comment by achmurzy** [comment]
However, it sounds like you guys are going to be interested in defoliating in different ways based on the land-use type of whichever ActiveSite gets passed into the 'InsectDefoliate' function. Let me know any details on how we should proceed.

**Comment by llmorreale** [comment]
It turns out we actually want to implement defoliation in a different way than they do in the Insect extension.  I now understand a bit better what Brian was saying above, and we also have a clearer idea of what we want. Sorry that we got started down the wrong path.  
Within the Insect CohortDefoliation.cs, the way they connect the defoliation algorithms to the succession extensions is to replace the BiomassCohorts.CohortDefoliation.Compute function (line 24 of Insect CohortDefoliation.cs, --> lines 9-25 in the BiomassCohorts library, CohortDefoliation.cs). 
Instead of implementing the Insect defoliation as done in Biomass Insects, we just want to mimic the way they overwrite the CohortDefoliation function.  We want the CohortDefoliation output to simply be a parameter that is taken from the LU+ text file. Specifically, we want the inputs to look exactly like the current prescriptions for removal of biomass within a land use: where you can specify species, age cohort, and then % removal, but having the % removal be % defoliation instead. This % would then the value that CohortDefoliation equals, instead of it calculating the value from other inputs. 
This would be an alternative/in addition to the biomass removal prescriptions, not a replacement.

**Comment by achmurzy** [comment]
Right okay, CohortDefoliation is a static class connecting to generalized cohort defoliation, it has an anonymous function (delegate) parameter Compute with the following function header: 
(ICohort cohort, ActiveSite site, int siteBiomass) 
Insects writes a custom function and replaces the Compute field. We can easily do the same for LU+, for each land-use type, and use the ActiveSite parameter to query the land-use type and get the right algorithm. Can we remove Biomass-Insects as a dependency?

**Comment by achmurzy** [comment]
Hi Luca, I've been working on updating LU+ to add defoliation functionality. The section of the code called 'LandCover' contains LandCoverChange types, now limited to NoChange and RemoveTrees. They implement an interface IChange -- this seems like the right place to put an InsectDefoliation to me, but right now LandUses assume only one type of LandCoverChange per LandUse type, and this affects the way the landuse.txt file is parsed. It may be worthwhile to extend this functionality so that many different types of LandCoverChanges can be applied to a single LandUse, if we intend to add functionality similar to InsectDefoliation later on. However, this may require modifying other parts of the model to account for multiple LandCoverChanges. Otherwise, if we want to apply insect defoliation and regular cohort harvesting to a land-use I'll have to do something more specialized. Let me know what you think.

**Comment by llmorreale** [comment]
Yes, we can remove Biomass-Insects as a dependency.  It is likely that at some point we will want to have both a regular cohort harvest and defoliation occur in the same land-use. Let's explore what it would take to modify the model to allow for multiple types of LandCoverChange in a single land use.  Once you have a good idea of the time + complexity of implementing multiple land-uses we can decide whether to pursue that change. Regardless, that seems like the perfect place to implement Defoliation in the code.

**Comment by achmurzy** [comment]
Hey Luca, it looks like there's three things we need to do:
-Generalize LandUse.cs 'LandCoverChange' field to a collection of some kind: array, list, etc.
-In Main.cs around Line 100 where the 'ApplyTo' method is called on the currentLandUse, we would need
to loop through the collection mentioned above to call 'ApplyTo' for each LandCoverChange on the current LandUse. This presents some methodological difficulties. For instance, if we are defoliating and harvesting in one time-step, are these applied in a specific order? Can they be applied to a cohort/ActiveSite simultaneously?
-Finally, we would need to be able to list an arbitrary number of LandCoverChanges for a LandUse in landuse.txt and be able to parse them

This wouldn't take long but I think the second point would be the most difficult part to think about -- simply applying multiple LandCoverChanges at each timestep might have unexpected effects and interactions which may be sequence dependent depending on which aspects of the grid-cell they affect. Let me know what you want to do

**Comment by llmorreale** [comment]
Let's go ahead with this plan.  I think the order should be decided by the order they are listed in the LU text file. This way users can decide for themselves whether there will be any methodological issues. On our end, we don't foresee any problematic interactions between defoliation and harvesting.

**Comment by achmurzy** [comment]
Alright I'll get right on it. One more thing: should the repeat harvest functionality be something that is true of all LandCoverChanges? Do you see needing to apply defoliation to a land use at the end of each timestep in the same way as we can now repeat harvesting? Or is this something that should be applied only to tree-removal? Or do we need a way to enable this for some LandCoverChanges and not for others?

**Comment by llmorreale** [comment]
We will definitely want this to work for defoliation as well. I think we will want it to be something that we can turn on/off for each individual Landuse.  Also, the next steps after we make these changes will be to make it so that it can not only repeat but ramp up or down over time. I'm not sure if this makes a difference to the way you want to implement it.

**Comment by achmurzy** [comment]
It's now possible to specify InsectDefoliation on LandUses but the Defoliate() function does nothing. I'm looking at how to specify a percent(%) biomass reduction for each tree species specified.

**Comment by achmurzy** [comment]
Hi Luca, I've been poking around the Succession libraries to try to understand how biomass moves through the model, and re-reading the recommendation made by Brian Miranda above. I think I misunderstood the strategy for applying defoliation. Rather than applying changes every time step, all we need to do is override the delegate and the Succession libraries will automatically apply the changes to cohorts when calculating NPP. 
What may or may not change every timestep are the parameters used to compute the change in biomass, allowing us to ramp up or down over time. So what I need to know is exactly how you would like defoliation to be calculated. The method header is as follows:
        public static double InsectDefoliate(ActiveSite active, ISpecies species, int cohortBiomass, int siteBiomass)
So we have access to each species in the cohort, that cohort's biomass, and the site biomass, which I assume is the sum of all the biomass across all cohorts. We can define a proportional reduction (80%, 95%, etc.), a scalar reduction (reduce biomass by 500, 1000, etc.), or some other function of insect density for each species. **Right now from how tree removal worked in LU+ previously we have a species specific proportional reduction in biomass. Is this sufficient for now?** 

We will also need to define a way to change parameters associated with defoliation for a site or cohort(species) across timesteps, and this will be the main work of the ApplyTo(ActiveSite site) method of InsectDefoliation as a type of LandCoverChange (IChange)

**Comment by achmurzy** [comment]
Looking a little closer, it looks like more work will be needed to allow modification of percentages values. They're currently stored in data structures defined by BiomassHarvest library (SpecificAgesCohortSelector.cs), and are locked up in private variables. CohortSelectors are a common data type for dealing with sets of species across LANDIS and I'll be able to define one that allows us to change harvesting/defoliation values across timesteps. I'll put this in the framework of LandCoverChanges to continue adding flexibility for modifying landscapes to LU+.

**Comment by llmorreale** [comment]
We want defoliation to be a species specific proportional reduction for the stated cohort age range (which is how LU+ does tree removal currently). It sounds like this is what you have currently implemented? If so then that is perfect.

I'm not sure I completely understand what you're describing with the modification of percentage values. Is this with regards to creating a land-use that increases or decreases its removal/defoliation over time?

**Comment by achmurzy** [comment]
Yea that's right: if we want to increase or decrease defoliation over time we would need to change the proportional reduction (defined as a percentage of current standing biomass). I'm working on changes to make this possible, as percentages are a private variable within the SiteHarvest library and hence unavailable for change across timesteps.

**Comment by llmorreale** [comment]
Adam, I think I may have misunderstood something.   The InsectDefoliate function is still empty? I thought that you had figured out how to implement it exactly like normal RemoveTrees, and that the difficulties came in figuring out how to have a LandUse change over time.

**Comment by achmurzy** [comment]
No upon finding out that percentage values were inaccessible for changing across time I started working on a way to make those modifiable. If you need to start testing/working with the defoliation function I can write up a quick version that uses the static percentages, though something else will ultimately be required.

**Comment by llmorreale** [comment]
If it wouldn't be too much extra work, a quick version that uses static percentages would be great, so we can begin testing things on our end.  Also, I don't know the structure, but would one possible way to have dynamic percentages be to provide it with a list of numbers as an original input instead of a single element and have it loop through the list over time?

**Comment by achmurzy** [comment]
Hi Luca, sorry for the wait, this change is turning out to be more and more involved as I look closer at it. It turned out that even static percentages required making changes to the way landuse.txt is parsed and percentages are stored in LU+ because the SiteHarvest and BiomassCohorts libraries hide the percentage values behind private members, so I couldn't access them to write the defoliation method. This poses problems if we want tree removal to use dynamic percentages in the future, because the CohortCutter machinery in the above libraries uses the hidden percentage values, and there is no way to change them without re-compiling the above libraries or replicating the functionality in LU+. 
Regardless, dynamic percentages are available for defoliation once I finish writing the defoliation method. Providing a list of percentages in LU+ would be one way, or a mathematical expression as a function of timestep, current biomass, etc. 
In the PnET extension (Cohort.cs, line 286) and BiomassSuccession(CohortBiomass.cs, line 103), defoliation is computed for each cohort, and currently defoliation percentages are given for age ranges within a cohort, for each species. The result is a range of possible defoliation values for a given species. The method header for defoliation functions is the following:
public static double InsectDefoliate(ActiveSite active, ISpecies species, int cohortBiomass, int siteBiomass)
The age of the calling cohort is apparently not available from these parameters, so I'm not sure how to apply a defoliation percentage based on age. If your models will assume a single defoliation value for each species no further changes are necessary, otherwise I can keep looking for a way to access cohort ages. Let me know what you think

**Comment by achmurzy** [comment]
Note also that if we want dynamic percentages we need to decide if this is applied to all species/cohort ages or only to specific species/age ranges.

**Comment by llmorreale** [comment]
I think that we can assume for now a single defoliation value per species and not have it vary with age.

**Comment by achmurzy** [comment]
Closing for update to 1.3
